[2024-04-27 20:58:07,387] 199 root -ERROR Error occured while creating data for prediction
[2024-04-27 20:58:07,388] 200 root -ERROR Error occured in python script named [d:/data_science/ml_projects/fpl_data_analysis/src/components/merging_raw_data.py] line number [182] error message ['numpy.ndarray' object is not callable]
